import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner"
import ErrorBoundary from "@/components/ui/error-boundary";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" data-theme="">
        <body className={inter.className} >
          <ErrorBoundary>
            <Header />
            {children}
          </ErrorBoundary>

          <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                background: 'linear-gradient(to right, #10b981, #3b82f6)',
                color: 'white',
                border: '1px solid #14b8a6',
              },
            }}
          />
        </body>
      </html>
    </ClerkProvider>
  );
}
